BulletinBoard/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using BulletinBoard.Models.BusinessLogic;
using BulletinBoard.Utils;
using BulletinBoard.Infrasructure;
using BulletinBoard.Models.Entities;

namespace BulletinBoard.Controllers;

/// <summary>
/// Deal with requests for login.
/// </summary>
public class LoginController : Controller
{
    private readonly ILoginLogic _loginLogic;

    /// <summary>
    /// Inject the business logic by DI Container.
    /// </summary>
    /// <param name="loginLogic">The business logic of LoginController.</param>
    public LoginController(ILoginLogic loginLogic)
    {
        _loginLogic = loginLogic;
    }

    /// <summary>
    /// Show Login page.
    /// </summary>
    /// <returns>The view of login page.</returns>
    public IActionResult Index()
    {
        return View();
    }

    /// <summary>
    /// Receive login form and validate Name and Password of a User. 
    /// If login success, redirect to <see cref="BulletinBoardController.Index()"/>.
    /// </summary>
    /// <param name="user">A User entity containing Name and Password.</param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [TypeFilter(typeof(FormValidationAttribute), Arguments = new object[] { ViewDataKeys.Name })]
    [TypeFilter(typeof(FormValidationAttribute), Arguments = new object[] { ViewDataKeys.Password })]
    public async Task<IActionResult> Index([Bind("Name,Password")] User user)
    {
        User? u = await _loginLogic.UserExists(user);

        if (u == null)
        {
            ViewData[ViewDataKeys.Password] = "Wrong name or password";
            return View();
        }

        UpdateSession(u);
        return RedirectToAction("Index", "BulletinBoard");
    }

    private void UpdateSession(User user)
    {
        HttpContext.Session.SetInt32(SessionKeys.UserId, user.Id!);
        HttpContext.Session.SetString(SessionKeys.DisplayName, user.DisplayName!);
    }
}

BulletinBoard/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using BulletinBoard.Utils;
using BulletinBoard.Models.Entities;
using BulletinBoard.Models.BusinessLogic;
using BulletinBoard.Infrasructure;

namespace BulletinBoard.Controllers;

/// <summary>
/// Deal with requests for registeration.
/// </summary>
public class RegisterController : Controller
{
    private readonly IRegisterLogic _registerLogic;

    /// <summary>
    /// Inject the business logic by DI Container.
    /// </summary>
    /// <param name="registerLogic">The business logic of RegisterController.</param>
    public RegisterController(IRegisterLogic registerLogic)
    {
        _registerLogic = registerLogic;
    }

    /// <summary>
    /// Show registeration page.
    /// </summary>
    /// <returns>The view of registeration page.</returns>
    public IActionResult Index()
    {
        return View();
    }

    /// <summary>
    /// Receive login form and validate Name, DisplayName and Password of a new User.
    /// </summary>
    /// <param name="user">A User entity containing Name, DisplayName and Password.</param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [TypeFilter(typeof(FormValidationAttribute), Arguments = new object[] { ViewDataKeys.Name })]
    [TypeFilter(typeof(FormValidationAttribute), Arguments = new object[] { ViewDataKeys.Password })]
    [TypeFilter(typeof(FormValidationAttribute), Arguments = new object[] { ViewDataKeys.DisplayName })]
    public async Task<IActionResult> Index([Bind("Name,Password,DisplayName")] User user)
    {
        user.RegisterDate = DateTime.Now;

        if (_registerLogic.UserNameExists(user.Name!))
        {
            ViewData[ViewDataKeys.Name] = "User name exists.";
        }
        else if (await _registerLogic.AddUserAsync(user) < 0)
        {
            TempData[TempDataKeys.Message] = "Register Error, please try again!";
        }
        else
        {
            TempData[TempDataKeys.Message] = "Register successfully!";
            return RedirectToAction("Index", "Login");
        }

        return View();
    }
}

BulletinBoard/Views/Login/Index.cshtml
@using BulletinBoard.Utils
@model BulletinBoard.Models.Entities.User
@{
    ViewData["Title"] = "Login";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">
            <form asp-controller="Login" asp-action="Index" method="post">
                <h2>Login</h2>
                <div class="form-group my-2">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                    @if (ViewData[ViewDataKeys.Name] != null)
                    {
                        <span class="text-danger">@ViewData[ViewDataKeys.Name]</span>
                    }
                </div>
                <div class="form-group my-2">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" type="password" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                    @if (ViewData[ViewDataKeys.Password] != null)
                    {
                        <span class="text-danger">@ViewData[ViewDataKeys.Password]</span>
                    }
                </div>
                <div class="form-group my-2">
                    <input type="submit" value="Enter" class="btn btn-primary" />
                </div>
            </form>
            <form method="get my-2">
                <button asp-controller="Register" asp-action="Index" class="btn btn-warning">Register</button>
            </form>
        </div>
    </div>
</div>