BulletinBoard/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using BulletinBoard.Models;
using BulletinBoard.Models.Entities;
using BulletinBoard.Models.BusinessLogic;
using BulletinBoard.Infrasructure;
using BulletinBoard.Utils;

namespace BulletinBoard.Controllers;

/// <summary>
/// Deal with requests for viewing posts and its replies. 
/// It also deals with requests for creating new posts.
/// </summary>
[ServiceFilter(typeof(AuthorizationAttribute))]
public class PostController : Controller
{
    private readonly IPostLogic _postLogic;

    /// <summary>
    /// Inject the business logic by DI Container.
    /// </summary>
    /// <param name="postLogic">The business logic of PostController.</param>
    public PostController(IPostLogic postLogic)
    {
        _postLogic = postLogic;
    }

    /// <summary>
    /// Show the post of given id and its replies.
    /// If there's no such id, redirect to NotFound().
    /// </summary>
    /// <param name="id">The Id of a Post</param>
    /// <returns>The view of the post and replies.</returns>
    public async Task<IActionResult> Index(int? id)
    {
        Post? post = await GetPost(id);

        if (post == null)
            return NotFound();

        return View(await GeneratePostViewModel(post));
    }

    private async Task<Post?> GetPost(int? id)
    {
        if (id == null)
            return null;
        return await _postLogic.GetPostByIdAsync(id);
    }

    private async Task<PostViewModel> GeneratePostViewModel(Post? post)
    {
        List<Reply>? replies = await _postLogic.GetRepliesByPostIdAsync(post!.Id);
        return new PostViewModel
        {
            Post = post,
            Replies = replies,
        };
    }

    /// <summary>
    /// Receive reply form and save the reply to database.
    /// </summary>
    /// <param name="id">Id of the Post that a user replies to.</param>
    /// <param name="newReply">Text of the Reply.</param>
    /// <returns>The view of post and replies.</returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(int id, string newReply)
    {
        int? userId = HttpContext.Session.GetInt32(SessionKeys.UserId);

        if (userId != null)
            await AddReply(new Reply
            {
                PostId = id,
                UserId = (int)userId!,
                SubmitTime = DateTime.Now,
                Text = newReply,
            });
        else
            ViewData[ViewDataKeys.Reply] = "Error session. Log in again may fix the problem.";

        return RedirectToAction("Index", new {id});
    }

    private async Task AddReply(Reply reply)
    {
        if (await _postLogic.AddReplyAsync(reply) < 0)
            ViewData[ViewDataKeys.Reply] = "Error creating reply.";
    }

    /// <summary>
    /// Show create post page.
    /// </summary>
    /// <returns>The view for creating a post.</returns>
    public IActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// Receive create-post form and validate Name and Password of a User.
    /// </summary>
    /// <param name="post">A Post entity containing Text.</param>
    /// <returns>If the post is saved to database successfully, redirect to <see cref="BulletinBoardController.Index()"/>.</returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Text")] Post post)
    {
        int? userId = HttpContext.Session.GetInt32(SessionKeys.UserId);

        if (userId != null)
        {
            post.SubmitTime = DateTime.Now;
            post.UserId = (int)userId;
            if (await AddPost(post))
                return RedirectToAction("Index", "BulletinBoard");
        }
        else
            ViewData[ViewDataKeys.Post] = "Error session. Log in again may fix the problem.";

        return View();
    }

    private async Task<bool> AddPost(Post post)
    {
        if (await _postLogic.AddPostAsync(post) < 0)
        {
            ViewData[ViewDataKeys.Post] = "Error creating post.";
            return false;
        }

        return true;
    }
}

BulletinBoard/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using BulletinBoard.Models.BusinessLogic;
using BulletinBoard.Infrasructure;
using BulletinBoard.Utils;
using BulletinBoard.Models.Entities;

namespace BulletinBoard.Controllers;

/// <summary>
/// Deal with requests for changing user's information.
/// </summary>
[ServiceFilter(typeof(AuthorizationAttribute))]
public class UserController : Controller
{
    private readonly IUserLogic _userLogic;

    /// <summary>
    /// Inject the business logic by DI Container.
    /// </summary>
    /// <param name="userLogic">The business logic of UserController.</param>
    public UserController(IUserLogic userLogic)
    {
        _userLogic = userLogic;
    }

    /// <summary>
    /// Show changing DisplayName page.
    /// </summary>
    /// <returns>The view of changing-DisplayName page</returns>
    public IActionResult ChangeDisplayName()
    {
        return View();
    }

    /// <summary>
    /// Receive changing-DisplayName form and validate display name.
    /// </summary>
    /// <param name="displayName">A new display name requested by user.</param>
    /// <returns>If the DisplayName is updated successfully, redirect to <see cref="BulletinBoardController.Index()"/>.</returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [TypeFilter(typeof(FormValidationAttribute), Arguments = new object[] { ViewDataKeys.DisplayName })]
    public async Task<IActionResult> ChangeDisplayName(string displayName)
    {
        int? userId = HttpContext.Session.GetInt32(SessionKeys.UserId);

        if (userId == null)
        {
            ViewData[ViewDataKeys.DisplayName] = "Session Error. Login again may fix the problem";
        }
        else if (await UpdateDisplayName(userId, displayName) == false)
        {
            ViewData[ViewDataKeys.DisplayName] = "Error changing name";
        }
        else
        {
            HttpContext.Session.SetString(SessionKeys.DisplayName, displayName);
            return RedirectToAction("Index", "BulletinBoard");
        }

        return View();
    }

    private async Task<bool> UpdateDisplayName(int? userId, string displayName)
    {
        User? currentUser = await _userLogic.GetUserByIdAsync((int)userId!);
        currentUser!.DisplayName = displayName;
        return await _userLogic.UpdateUserAsync(currentUser);
    }
}

BulletinBoard/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BulletinBoard.Utils

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulletinBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulletinBoard.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="BulletinBoard" asp-action="Index">BulletinBoard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (Context.Session.GetInt32(SessionKeys.UserId) != null)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Create">Create
                                    Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User"
                                asp-action="ChangeDisplayName">Change DisplayName</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark">Hello, @Context.Session.GetString(SessionKeys.DisplayName)</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @if (TempData[TempDataKeys.Message] != null)
    {
        <script>alert('@TempData[TempDataKeys.Message]');</script>
    }
</body>

</html>